services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8000:8000

  database:
    image: postgres:17-alpine
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DATABASE: dj_db

  adminer:
    image: adminer:latest
    ports: 
      - 8080:8080
