volumes:
  ollama:
services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama:rw


  bot:
    build: 
      dockerfile: dockerfile
      context: .
